services:
  - type: web
    name: url-checker-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SHEET_URL
        value: 14Yk8UnQviC29ascf4frQfAEDWzM2_bp1UloRcnW8ZCg
        sync: false
      - key: URL_COLUMNS
        value: N,O,P,Q,R,S,T,U,V,W,X,Y,Z,AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL
        sync: false
      - key: TESTING_MODE
        value: false
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false 